export const PERMISSIONS = {
  // Super Admin Level Permissions
  TRACK_FINANCE: 'TRACK_FINANCE',
  TRACK_ORGANIZATIONS: 'TRACK_ORGANIZATIONS',
  TRACK_USERS: 'TRACK_USERS',
  TRACK_STUDENTS: 'TRACK_STUDENTS',
  MANAGE_ROLES: 'MANAGE_ROLES',
};

export const PERMISSION_LABELS = {
  [PERMISSIONS.TRACK_FINANCE]: 'Tracking Finance',
  [PERMISSIONS.TRACK_ORGANIZATIONS]: 'Tracking Organizations',
  [PERMISSIONS.TRACK_USERS]: 'Tracking Users',
  [PERMISSIONS.TRACK_STUDENTS]: 'Tracking Students',
  [PERMISSIONS.MANAGE_ROLES]: 'Managing Roles',
};
